gamera_directory = "/mnt/archive/soc/data/"
output_directory = "/mnt/archive/soc/data/"
forward_psf_model_path = "/home/soc/simpunch/synthetic_forward_psf.fits"
backward_psf_model_path = "/home/soc/simpunch/synthetic_backward_psf.fits"
wfi_quartic_backward_model_path = "/home/soc/simpunch/wfi_quartic_backward_coeffs.fits"
nfi_quartic_backward_model_path = "/home/soc/simpunch/nfi_quartic_backward_coeffs.fits"
wfi_quartic_model_path = "/home/soc/simpunch/wfi_quartic_coeffs.fits"
nfi_quartic_model_path = "/home/soc/simpunch/nfi_quartic_coeffs.fits"
num_repeats = 1
generate_new = true
generate_full_day = false
update_database = false
transient_probability = 0.0
shift_pointing = false
surrounding_cadence = 0.5
