gamera_directory = "/Users/jhughes/Desktop/noaa_run/"
output_directory = "/Users/jhughes/Desktop/noaa_run/"
forward_psf_model_path = "/Users/jhughes/Desktop/noaa_run/synthetic_forward_psf.fits"
backward_psf_model_path = "/Users/jhughes/Desktop/noaa_run/synthetic_backward_psf.fits"
wfi_quartic_backward_model_path = "/Users/jhughes/Desktop/noaa_run/wfi_quartic_backward_coeffs.fits"
nfi_quartic_backward_model_path = "/Users/jhughes/Desktop/noaa_run/nfi_quartic_backward_coeffs.fits"
wfi_quartic_model_path = "/Users/jhughes/Desktop/noaa_run/wfi_quartic_coeffs.fits"
nfi_quartic_model_path = "/Users/jhughes/Desktop/noaa_run/nfi_quartic_coeffs.fits"
num_repeats = 1
generate_new = true
generate_full_day = false
update_database = false
transient_probability = 0.0
shift_pointing = false
surrounding_cadence = 0.5
