file_tb = 'DOICMEM_00912all_plasma_GLOBAL_step0005_dcmer0000_azequi_TB.fits'
file_pb ='DOICMEM_00912all_plasma_GLOBAL_step0005_dcmer0000_azequi_PB.fits'
out_dir = "/Users/jhughes/Desktop/noaa_run/"
start_time = "2025-02-21T04:04:04"
backward_psf_model_path = "/Users/jhughes/Desktop/noaa_run/synthetic_backward_psf.fits"
wfi_quartic_backward_model_path = "/Users/jhughes/Desktop/noaa_run/wfi_quartic_backward_coeffs.fits"
nfi_quartic_backward_model_path = "/Users/jhughes/Desktop/noaa_run/nfi_quartic_backward_coeffs.fits"
transient_probability = 0.0
shift_pointing = false
